<nav class="row">
    <div class="col">
        <strong>Logo da Aplicação</strong>
    </div>
    <div class="col text-end">
        <a class="btn btn-outline-dark" href="/">Home</a>
        <a class="btn btn-outline-dark" href="/admin">Admin</a>
        <a class="btn btn-outline-dark" href="/admin/usuarios">Usuarios</a>
        <a class="btn btn-outline-danger" href="/login">Sair</a>
    </div>
</nav>

<hr>