<h1>Usuarios</h1>

<?php

include dirname(__DIR__)."/conexao.php";

$resultado = $pdo->query("SELECT * FROM tb_users");

?>
<table class="table table-striped table-hover">
    <thead class="table-dark">
        <tr>
            <th>#ID</th>
            <th>Nome</th>
            <th>Email</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php 
            foreach ($resultado->fetchAll() as $user) {
                echo "
                    <tr>
                        <td>{$user['id']}</td>
                        <td>{$user['nome']}</td>
                        <td>{$user['email']}</td>
                        <td>
                            <button class='btn btn-warning btn-sm'>Editar</button>
                            <button class='btn btn-danger btn-sm'>Excluir</button>
                        </td>
                    </tr>
                ";
            }
        ?>
    </tbody>
</table>

